# Generated by Django 3.1 on 2020-08-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poporimember', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '이용자 리스트', 'verbose_name_plural': 'popori 이용자 ^^'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth',
            field=models.DateTimeField(null=True),
        ),
    ]
